import Head from "next/head";
import { Box } from "@mui/material";
export default function Home() {
  return (
    <>
      <Head>
        <title>Home Page</title>
        <meta property="og:title" content="Welcome to Our Website" />
        <meta
          property="og:description"
          content="Discover amazing products and services"
        />
        <meta property="og:type" content="website" />
        <meta property="og:url" content="http://localhost:3001/" />
        <meta property="og:image" content="http://localhost:3001/home-og.jpg" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>Hello</Box>
    </>
  );
}
